Company/urls.py
from django.urls import path

from Company.views import index, create, console, view, delete, tools

app_name = 'company'

urlpatterns =[
    path('company/sample', index, name='index'),
    path('company/create', create, name='create'),
    path('company/console/<str:Project_Name>', console, name='console'),
    path('company/<str:Project_Name>', view, name='view'),
    path('company/tools/<str:Project_Name>', tools, name='tools'),
    path('company/delete/<str:Project_Name>', delete, name='delete')
]

core/urls.py
from django.urls import path
from core.views import indexweb, dashboard, search_themes, notify, updateuser

app_name = 'core'

urlpatterns =[
    path('', indexweb, name='indexweb'),
    path('dashboard', dashboard, name='dashboard'),
    path('search/themes', search_themes, name='search_themes'),
    path('notification', notify, name='notify'),
    path('profile/<str:username>/', updateuser, name='updateuser'),


]

feeback/urls.py
from django.urls import path

from feeback.views import feedback, thankyou

app_name = 'feedback'

urlpatterns =[
    path('feedback', feedback, name='feedback'),
    path('feedback/thankyou', thankyou, name='thankyou'),


]

restaurant/urls.py
from django.urls import path

from restaurant.views import index, create, console, view, tools, delete

app_name = 'restaurant'

urlpatterns =[
    path('restaurant/sample', index, name='index'),
    path('restaurant/create', create, name='create'),
    path('restaurant/console/<str:projectname>', console, name='console'),
    path('restaurant/<str:projectname>', view, name='view'),
    path('restaurant/tools/<str:projectname>', tools, name='tools'),
    path('restaurant/delete/<str:projectname>', delete, name='delete')
]

resume/urls.py
from django.urls import path

from resume.views import index, create, console, view, delete, tools

app_name = 'resume'

urlpatterns =[
    path('resume/sample', index, name='index'),
    path('resume/create', create, name='create'),
    path('resume/console/<str:Project_Name>', console, name='console'),
    path('resume/<str:Project_Name>', view, name='view'),
    path('resume/tools/<str:Project_Name>', tools, name='tools'),
    path('resume/delete/<str:Project_Name>', delete, name='delete')
]

web_demo/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('theme1.urls')),
    path('', include('core.urls')),
    path('', include('restaurant.urls')),
    path('', include('resume.urls')),
    path('', include('Company.urls')),
    path('', include('feeback.urls')),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),

]

urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'You Web | Admin'
admin.site.site_title = 'You Web'

core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.conf import settings
# Create your models here.
class notification(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='images/', blank=True, null=True, )
    date = models.DateTimeField(auto_now_add=True)
    link = models.CharField(max_length=1000)

core/forms.py
from django import forms
from django.contrib.auth.models import User


class updateprofile(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name',]

core/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.
from Company.models import CompanyDb
from core.forms import updateprofile
from core.models import notification
from restaurant.models import RestDb
from resume.models import resumeDb
from theme1.models import theme1


def indexweb(request):
    return render(request, 'core/index.html')


def dashboard(request):
    if request.user.is_authenticated:
        th1 = theme1.objects.all()
        th2 = RestDb.objects.all()
        th3 = resumeDb.objects.all()
        th4 = CompanyDb.objects.all()
        return render(request, 'core/dashboard.html', {'th1': th1, 'th2':th2, 'th3':th3, 'th4':th4})
    else:
        return redirect('account_login')


def search_themes(request):
    if request.user.is_authenticated:
        return render(request, 'core/search_themes.html',)
    else:
        return redirect('account_login')

#
# def search_themes(request):
#     if request.user.is_authenticated:
#         listTh1 = theme1.objects.all()
#         cruds = crud.objects.all()
#         return render(request, 'core/search_themes.html', {'listTh1': listTh1, 'cruds': cruds})
#     else:
#         return redirect('account_login')
def notify (request):
    notify = notification.objects.all()
    return render(request, 'core/notification.html',{'notify':notify})


def updateuser(request, username):
    pro = User.objects.get(username=username)
    pros = User.objects.filter(username=username)
    form = updateprofile(request.POST or None, instance=pro)
    if form.is_valid():
        form.save()
        return redirect('core:dashboard')

    return render(request, 'core/profile.html', {'form': form, 'pro': pro,'pros':pros })

templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YouWeb</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="{% static 'theme1/css/styles.css'  %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">You Web</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'core:indexweb' %}">Home</a></li>
            {% if user.is_authenticated  %}
                <li><a href="{% url 'core:dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'core:search_themes' %}">Themes</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'core:notify' %}">Notification &nbsp&nbsp </a></li>
                    <li><a href="{% url 'core:updateuser' user%}">Profile</a></li>
                    <li><a href="{% url 'feedback:feedback'%}">Feedback</a></li>
                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                  </ul>
                </li>
            {% else %}
                  <li><a href="{% url 'account_login' %}">Login</a></li>
                  <li><a href="{% url 'account_signup' %}">Signup</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block content %}

    {% endblock %}


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>

templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Dashboard</h1>
        <div class="row">
            <div class="col-lg-12">
                <h2>Your Projects</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
               {% for th2 in th2 %}
                    {% if user.id == th2.user_id %}
                        <div class="col-lg-3 dash-list">
                            <div class="col-lg-12 dash-list-full">
                                <div class="row">
                                    <img src="https://d3uzz33g1d6j2w.cloudfront.net/img/pages/fe-thumb/italiano-900x600_b9db795e6f953cf2a178ed8122a04f94.jpg" class="img-responsive"  alt="">
                                </div>
                                <div class="row body-dash-list">
                                    <div class="col-lg-12">
                                        <div class="row"><h4><a href="{% url 'restaurant:view' th2.projectname %}">{{ th2.projectname }}</a></h4></div>
                                        <h6>Type:&nbsp {{ th2.Type }}</h6>
                                        <div class="row"><h6>Created: {{ th2.Created }}</h6></div>
                                    </div>
                                </div>
                                <div class="row">
                                   <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-edit"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'restaurant:console' th2.projectname %}">&nbsp;Edit</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-tools"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'restaurant:tools' th2.projectname %}">&nbsp;Tools</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default" style="border-right: none;"><i class="fas fa-trash-alt"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'restaurant:delete' th2.projectname %}">&nbsp;Delete</a></button>
                                      </div>
                                   </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                {% for th3 in th3 %}
                    {% if user.id == th3.user_id %}
                        <div class="col-lg-3 dash-list">
                            <div class="col-lg-12 dash-list-full">
                                <div class="row">
                                    <img src="{% static 'resume/img/sample.jpg' %}" class="img-responsive"  alt="">
                                </div>
                                <div class="row body-dash-list">
                                    <div class="col-lg-12">
                                        <div class="row"><h4><a href="{% url 'resume:view' th3.Project_Name %}">{{ th3.Project_Name }}</a></h4></div>
                                        <h6>Type:&nbsp{{ th3.Type }}</h6>
                                        <div class="row"><h6>Created: {{ th3.Created }}</h6></div>
                                    </div>
                                </div>
                                <div class="row">
                                   <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-edit"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'resume:console' th3.Project_Name%}">&nbsp;Edit</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-tools"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'resume:tools' th3.Project_Name %}">&nbsp;Tools</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default" style="border-right: none;"><i class="fas fa-trash-alt"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'resume:delete' th3.Project_Name%}">&nbsp;Delete</a></button>
                                      </div>
                                   </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
               {% endfor %}
               {% for th4 in th4 %}
                    {% if user.id == th4.user_id %}
                        <div class="col-lg-3 dash-list">
                            <div class="col-lg-12 dash-list-full">
                                <div class="row">
                                    <img src="{% static 'Company/img/th4.jpg' %}" class="img-responsive"  alt="">
                                </div>
                                <div class="row body-dash-list">
                                    <div class="col-lg-12">
                                        <div class="row"><h4><a href="{% url 'company:view' th4.Project_Name %}">{{ th4.Project_Name }}</a></h4></div>
                                        <h6>Type:&nbsp{{ th4.Type }}</h6>
                                        <div class="row"><h6>Created: {{ th4.Created }}</h6></div>
                                    </div>
                                </div>
                                <div class="row">
                                   <div class="btn-group btn-group-justified" role="group" aria-label="...">
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-edit"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'company:console' th4.Project_Name%}">&nbsp;Edit</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default"><i class="fas fa-tools"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'company:tools' th4.Project_Name %}">&nbsp;Tools</a></button>
                                      </div>
                                      <div class="btn-group btn-dash-edit" role="group">
                                        <button type="button" class="btn btn-default" style="border-right: none;"><i class="fas fa-trash-alt"></i>
                                            <a style="text-decoration: none; color: hsla(0,0%,100%,.75);" href="{% url 'company:delete' th4.Project_Name%}">&nbsp;Delete</a></button>
                                      </div>
                                   </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
               {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container" style="padding-top: 50px;">
        <h1 class="text-center">Hello and Welcome to You Web</h1>
        <h2 class="text-center" style="padding-top: 15px;">One Platform to </h2>
        <h2 class="text-center">Create, Connect and Explore</h2>
    </div>
{% endblock %}

templates/core/notification.html
{% extends 'core/base.html' %}
{% block content %}
        <div class="container">
            <div class="row" style="padding-bottom: 10px;">
                <h1>Notifications</h1>
            </div>
            {% for notify in notify %}
                <div class="col-lg-12 theme-list-col"  style="margin-bottom: 20px;">
                <div class="col-lg-3">
                    <img src="{{ notify.image.url }}" class="img img-responsive" alt="">
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <h3 style="margin-top: 5px;">{{ notify.title }}</h3>
                    </div>
                    <div class="row" style="padding-bottom: 25px;">
                        <p>{{ notify.body }}</p>
                    </div>
                    <div class="row">
                       <div class="col-lg-6 col-sm-6">
                            <a href="{{ notify.link }}">Click here</a>
                       </div>
                         <div class="col-lg-6 col-sm-6">
                            <p class="text-right" style="margin: 0;">{{ notify.date }}</p>
                       </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}

templates/core/profile.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <div class="col-lg-12">
            <h1>Profile <span style="font-size: 20px;">(update your profile)</span></h1>
            <div class="col-lg-6 col-lg-push-3" style="padding-top: 25px;">
                 {% for profile in pros %}
                    {% if profile.username == user.username %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button class="btn btn-info" style="margin-top: 15px;" type="submit">Confirm</button>
                        </form>
                        <h4 style="padding-top: 15px;"><a href="{% url 'account_change_password' %}">Reset / Change your password</a></h4>
                    {% else %}
                        <h2>Seems like this is not your Account!! </h2>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/core/search_themes.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Search Themes here ...</h1>
        <div class="row theme-list-row" >
            <div class="col-lg-12 theme-list-com">
                <div class="col-lg-12 theme-list-col">
                    <div class="col-lg-3 theme-list-color">
                        <img src="https://d3uzz33g1d6j2w.cloudfront.net/img/pages/fe-thumb/italiano-900x600_b9db795e6f953cf2a178ed8122a04f94.jpg" class="img-responsive"  alt="">
                    </div>
                    <div class="col-lg-9">
                        <h3 style="letter-spacing: 1px; color: whitesmoke; margin-top: 10px;">Restaurant Theme</h3>
                        <p style="letter-spacing: 1px;">Restaurant Them is an elegant free restaurant. Built on YouWeb Engine, uses Bootsrap 3.3.7 ,
                            HTML, CSS and Javascript Bootstrap HTML template that comes with a variety
                            of useful page elements that will enable you that create a classy restaurant website really fast. </p>
                        <div class="row theme-list-btn-row">
                            <button class="btn btn-primary btn-theme-list-view"><a style="text-decoration: none; color: whitesmoke" href="{% url 'restaurant:index' %}">View</a></button>
                            <button class="btn btn-primary btn-theme-list-edit"><a style="text-decoration: none; color: whitesmoke" href="{% url 'restaurant:create' %}">Edit</a></button>
                        </div>
                    </div>
{#                    <div class="col-lg-2">#}
{#                        <div class="panel panel-default user-rate-panel" style="margin: 0px;">#}
{#                          <div class="panel-heading"><h4 class="text-center" style="margin: 0px;color: black ">User Rating's</h4></div>#}
{#                          <div class="panel-body">#}
{#                            <h4 class="text-center" style="padding-top: 7px;"><i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star"></i></h4>#}
{#                            <h4 class="text-center" style="padding-top: 15px;">Very Good</h4>#}
{#                          </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
        <div class="row theme-list-row" >
            <div class="col-lg-12 theme-list-com">
                <div class="col-lg-12 theme-list-col">
                    <div class="col-lg-3 theme-list-color">
                        <img src="{%  static 'resume/img/sample.jpg'  %}" style="height: " class="img-responsive"  alt="">
                    </div>
                    <div class="col-lg-9">
                        <h3 style="letter-spacing: 1px; color: whitesmoke; margin-top: 10px;">Resume Theme</h3>
                        <p style="letter-spacing: 1px;">Resume Theme is beautiful Theme built for resumes and Portfalio. Built on YouWeb Engine, uses Bootsrap 3.3.7 ,
                            HTML, CSS and Javascript. Bootstrap HTML template that comes with a variety of useful page elements that will enable you that create a classy restaurant website really fast.  </p>
                        <div class="row theme-list-btn-row">
                            <button class="btn btn-primary btn-theme-list-view"><a style="text-decoration: none; color: whitesmoke" href="{% url 'resume:index' %}">View</a></button>
                            <button class="btn btn-primary btn-theme-list-edit"><a style="text-decoration: none; color: whitesmoke" href="{% url 'resume:create' %}">Edit</a></button>
                        </div>
                    </div>
{#                    <div class="col-lg-2">#}
{#                        <div class="panel panel-default user-rate-panel" style="margin: 0px;">#}
{#                          <div class="panel-heading"><h4 class="text-center" style="margin: 0px;color: black ">User Rating's</h4></div>#}
{#                          <div class="panel-body">#}
{#                            <h4 class="text-center" style="padding-top: 7px;"><i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i></h4>#}
{#                            <h4 class="text-center" style="padding-top: 15px;">Very Good</h4>#}
{#                          </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
        <div class="row theme-list-row" >
            <div class="col-lg-12 theme-list-com">
                <div class="col-lg-12 theme-list-col">
                    <div class="col-lg-3 theme-list-color">
                        <img src="{%  static 'Company/img/th4.jpg'  %}" class="img-responsive"  alt="">
                    </div>
                    <div class="col-lg-9">
                        <h3 style="letter-spacing: 1px; color: whitesmoke; margin-top: 10px;">Company Theme</h3>
                        <p style="letter-spacing: 1px;">Company Theme is beautiful Theme built for Small Startups and Small Scale Company. Built on YouWeb Engine, uses Bootsrap 3.3.7 ,
                            HTML, CSS and Javascript. Bootstrap HTML template that comes with a variety of useful page elements that will enable you that create a classy restaurant website really fast.  </p>
                        <div class="row theme-list-btn-row">
                            <button class="btn btn-primary btn-theme-list-view"><a style="text-decoration: none; color: whitesmoke" href="{% url 'company:index' %}">View</a></button>
                            <button class="btn btn-primary btn-theme-list-edit"><a style="text-decoration: none; color: whitesmoke" href="{% url 'company:create' %}">Edit</a></button>
                        </div>
                    </div>
{#                    <div class="col-lg-2">#}
{#                        <div class="panel panel-default user-rate-panel" style="margin: 0px;">#}
{#                          <div class="panel-heading"><h4 class="text-center" style="margin: 0px;color: black ">User Rating's</h4></div>#}
{#                          <div class="panel-body">#}
{#                            <h4 class="text-center" style="padding-top: 7px;"><i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i>#}
{#                                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i></h4>#}
{#                            <h4 class="text-center" style="padding-top: 15px;">Very Good</h4>#}
{#                          </div>#}
{#                        </div>#}
{#                    </div>#}
                </div>
            </div>
        </div>
        <div class="row text-center" style="padding-top: 50px;">
            <a class=" btn btn-success"    href="{% url 'feedback:feedback' %}"> Request a Theme </a>
        </div>
    </div>

{% endblock %}

templates/core/theme1list.html
<h2>hi</h2>
{#{% for listTh1 in listTh1 %}#}
{#    {{ listTh1.projectname }}#}
{#{% endfor %}#}

templates/core/theme2.html
{{ user.id }}